/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as vestingToken1Sol from "./VestingToken.1.sol";
export type { vestingToken1Sol };
import type * as vestingTokenSol from "./VestingToken.sol";
export type { vestingTokenSol };
